id: PA53C1FCA
initial_creation_type: ocr
source_metadata:
  volumes:
    8b3629df89264132bb208e28c851f563:
      base_file: v107.txt
      image_group_id: I1PD95952
      title: དེ་ཁོ་ན་ཉིད་བསྡུས་པའི་དཀའ་འགྲེལ།
      total_pages: 1891
      volume_number: 107
